# Generated by Django 4.1.11 on 2023-09-27 02:45

from django.db import migrations
from datetime import datetime

def set_common_date(apps, schema_editor):
    Donor_Info = apps.get_model('myapp', 'Donor_Info')
    common_date = datetime.strptime('20/11/2023', '%d/%m/%Y')

    # Update all records with the common date
    Donor_Info.objects.update(donation_date=common_date)

class Migration(migrations.Migration):

    dependencies = [
        # Add any dependencies here if needed
    ]

    operations = [
        migrations.RunPython(set_common_date),
    ]

