# Generated by Django 4.1.11 on 2023-09-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='donor_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group_donated', models.BooleanField(default=False)),
                ('geo_location', models.CharField(max_length=100)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_saver.BloodGroup')),

            ],
        ),
    ]
