# Generated by Django 4.1.11 on 2023-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_saver', '0002_rename_donor_info_donorinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodgroup',
            options={'verbose_name': 'db_blood_group'},
        ),
        migrations.AlterModelOptions(
            name='donorinfo',
            options={'verbose_name': 'db_donor_info'},
        ),
    ]
